format = """
${custom.git_config_email}\
$directory\
$git_branch\
$git_status\
${custom.git_wip}\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
$scala\
$terraform\
$python\
$time\n  \
[ó±žª](fg:iris) \
"""

palette = "rose-pine"

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
format = "[î‚¶](fg:overlay)[ $path ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
'~' = "ï…¹"
Documents = "ó°ˆ™"
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "

[battery]

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[î‚¶](fg:overlay)[ $symbol $branch ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = "ï˜"

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[î‚¶](fg:overlay)([$all_status$ahead_behind]($style))[î‚´](fg:overlay) '
up_to_date = '[ âœ“ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[Â»\($count\)](bg:overlay fg:iris)'
deleted = '[âœ˜\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[â‡¡\(${count}\)](bg:overlay fg:foam)'
diverged = 'â‡•[\[](bg:overlay fg:iris)[â‡¡\(${ahead_count}\)](bg:overlay fg:foam)[â‡£\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[â‡£\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = false
format = "[î‚¶](fg:overlay)[ $time ó°¥” ]($style)[î‚´](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[î‚¶](fg:overlay)[ ï£¿ $user ]($style)[î‚´](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[custom.git_config_email]
description = "Output the current git user's configured email address."
command = "git config user.email"
format = "\n[$symbol( îœ‰ $output)]($style) "
# Only when inside git repository
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
style = "text"

[custom.git_wip]
when = "test -d .git && git --no-pager log -1 --format='%<(100,trunc)%s' | grep -s WIP"
format = "[ðŸš¨WIP]($style) "
style = "bold fg:#bf5700"

[sudo]
style = 'bold green'
symbol = 'ðŸ˜µâ€ðŸ’» '
disabled = false

[status]
style = "bg:overlay fg:rose"
format = "[î‚¶](fg:overlay)[ $symbol$common_meaning ]($style)[î‚´](fg:overlay)"
#format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

# Languages

[c]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜ž "

[elixir]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î‰µ "

[elm]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜¬ "

[golang]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜§ "

[haskell]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î· "

[java]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î‰– "

[julia]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "î˜¤ "

[nodejs]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "ó°Ž™ "

[rust]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "îž¨"

[scala]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = "îœ· "

[terraform]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = 'ó±¢ '

[python]
style = "bg:overlay fg:pine"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay) "
disabled = false
symbol = 'îœ¼ '

